Fix Markdown Line Length
render-engine/render-engine-parser pull request #16
Opened 2024-10-22 18:58 UTC by john0isaac

# Description
This PR fixes line length in the markdown to pass the workflow.

## Checklist
- [x] I have read the contributing guidelines.
- [-] I have written tests for the changes, if applicable.
- [x] I have added necessary documentation.

### Related Issues
Please reference related issues here:

2024-10-26 09:06 UTC, kjaymiller commented
I'm personally not a fan of [MD013](https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md) as I think some markdown parsers will mess it up and adding arbitrary `\n` into text in the middle of sentences doesn't seem right. 

I don't mind the other two fixes but I think the actual change should be to add a `markdownlint.jsonc` that ignores MD013.

2024-10-26 09:09 UTC, kjaymiller commented
for more information - https://github.com/DavidAnson/markdownlint-cli2?tab=readme-ov-file#markdownlint-cli2jsonc

2024-10-26 09:10 UTC, kjaymiller requested changes

2024-10-26 09:10 UTC, kjaymiller commented on README.md
see other comments

2024-10-26 14:26 UTC, john0isaac commented
done

2024-10-28 14:13 UTC, kjaymiller approved these changes

2024-10-28 14:14 UTC, kjaymiller commented
Did we check that the tests pass.. I don't know if I have a linter for it or not.

2024-10-28 18:15 UTC, john0isaac commented
Which tests?
All of the currently configured workflows passed.

Are there any other tests you are talking about?

2024-10-29 00:52 UTC, merged